<?php include("include/config.php"); ?>
<!DOCTYPE html>
<html lang="en">
<head>
	<title><?php echo $page_title; ?></title>
	<!--Basic META tags-->
	<meta charset="utf-8"></meta>
	<meta content="width=device-width, initial-scale=1.0" name="viewport"></meta>
	<meta content="bullet dodge, coms309, game, online, friends" name="keywords"></meta>
	<meta content="<?php echo $page_description;?>" name="description"></meta>
	<!--Open Graph Protocol-->
	<meta property="og:title" content="<?php echo $page_title; ?>" />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="http://www.proj-309-18.cs.iastate.edu" />
	<meta property="og:description" content="<?php echo $page_description;?>" />
	<!-- <meta property="og:image" content="http://www.proj-309-18.cs.iastate.edu" /> -->
	<!-- Icons (Sizing order is weird, I'm not sure why. This is generated by a favicon generator and ordered for a reason, don't change it) -->
	<!-- <link rel="apple-touch-icon" sizes="57x57" href="media/icon/apple-touch-icon-57x57.png">
	<link rel="apple-touch-icon" sizes="114x114" href="media/icon/apple-touch-icon-114x114.png">
	<link rel="apple-touch-icon" sizes="72x72" href="media/icon/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="144x144" href="media/icon/apple-touch-icon-144x144.png">
	<link rel="apple-touch-icon" sizes="60x60" href="media/icon/apple-touch-icon-60x60.png">
	<link rel="apple-touch-icon" sizes="120x120" href="media/icon/apple-touch-icon-120x120.png">
	<link rel="apple-touch-icon" sizes="76x76" href="media/icon/apple-touch-icon-76x76.png">
	<link rel="apple-touch-icon" sizes="152x152" href="media/icon/apple-touch-icon-152x152.png">
	<link rel="apple-touch-icon" sizes="180x180" href="media/icon/apple-touch-icon-180x180.png">
	<link rel="icon" type="image/png" href="media/icon/favicon-192x192.png" sizes="192x192">
	<link rel="icon" type="image/png" href="media/icon/favicon-160x160.png" sizes="160x160">
	<link rel="icon" type="image/png" href="media/icon/favicon-96x96.png" sizes="96x96">
	<link rel="icon" type="image/png" href="media/icon/favicon-16x16.png" sizes="16x16">
	<link rel="icon" type="image/png" href="media/icon/favicon-32x32.png" sizes="32x32"> 
	<meta name="msapplication-TileColor" content="#2b5797">
	<meta name="msapplication-TileImage" content="media/icon/mstile-144x144.png"> -->
	<!--[if IE]><link rel="shortcut icon" href="/media/icon/favicon.ico" /><![endif]-->
	<!--FONTS-->
	<!--Common Stylesheet-->
	<!--<link href="library/font-awesome-4.2.0/css/font-awesome.min.css" rel="stylesheet">-->
	<link href="library/bootstrap-3.3.1-dist/css/bootstrap.min.css" rel="stylesheet">
	<link href="library/font-awesome-4.3.0/css/font-awesome.min.css" rel="stylesheet">
	<link href="library/css/app.css" rel="stylesheet">
	<link href="library/forkio/all.css" rel="stylesheet">
	<link href="http://fonts.googleapis.com/css?family=Montserrat:400,700|Source+Sans+Pro:400,700,400italic,700italic" rel="stylesheet" type="text/css">
	<!--Page-related Stylesheet-->
	<?php
	if(isset($page_stylesheet)){
		foreach($page_stylesheet as &$sheet){
			echo "<link rel=\"stylesheet\" href=\"", $sheet, "\" />";
		}
	}
	?>
	<!--<link href="library/css/sitewide.css" rel="stylesheet">-->
</head>
<body>
	
	<?php include($page_content); ?>

	<!--Common Scripts-->
	<script src="https://cdn.socket.io/socket.io-1.3.4.js"></script>
	<script type="text/javascript" src="library/jquery-2.1.1/jQuery-2.1.1.js"></script>
	<script type="text/javascript" src="library/bootstrap-3.3.1-dist/js/bootstrap.min.js"></script>
	<!--Page-related Scripts-->
	<?php
	if(isset($page_javascript)){
		foreach($page_javascript as &$script){
			echo "<script type=\"text/javascript\" src=\"", $script , "\"></script>\n";
		}
	}
	?>
	<script type="text/javascript" src="library/snap/snap.js"></script>
	<!--<script type="text/javascript" src="library/js/sitewide.js"></script>-->
	<script type="text/javascript" src="library/js/app.js"></script>
	</body>
</html>